import { PrismaClient } from '@prisma/client';

export async function seedCities(prisma: PrismaClient) {
  console.log('🏙 Seeding cities...');

  const cities = [
    { name: 'C.G. ROAD', code: 'CGR', state: 'Gujarat' },
    { name: 'RATANPOLE', code: 'RAT', state: 'Gujarat' },
    { name: 'BAPUNAGAR', code: 'BAP', state: 'Gujarat' },
    { name: 'BOPAL', code: 'BOP', state: 'Gujarat' },
    { name: 'GOTA', code: 'GOT', state: 'Gujarat' },
    { name: 'GURUKUL', code: 'GUR', state: 'Gujarat' },
    { name: 'KALUPUR', code: 'KAL', state: 'Gujarat' },
    { name: 'MADHUPURA', code: 'MAD', state: 'Gujarat' },
    { name: 'NARODA', code: 'NAR', state: 'Gujarat' },
    { name: 'NAROL', code: 'NA1', state: 'Gujarat' },
    { name: 'ODHAV', code: 'ODH', state: 'Gujarat' },
    { name: 'ASHRAM ROAD', code: 'ASH', state: 'Gujarat' },
    { name: 'RAKHIYAL', code: 'RAK', state: 'Gujarat' },
    { name: 'CHANGODAR', code: 'CHA', state: 'Gujarat' },
    { name: 'SATELLITE', code: 'SAT', state: 'Gujarat' },
    { name: 'RANIP', code: 'RAN', state: 'Gujarat' },
    { name: 'SCIENCE CITY', code: 'SCI', state: 'Gujarat' },
    { name: 'SARKHEJ', code: 'SAR', state: 'Gujarat' },
    { name: 'VATVA', code: 'VAT', state: 'Gujarat' },
    { name: 'CHANDKHEDA', code: 'CH1', state: 'Gujarat' },
    { name: 'MANINAGAR', code: 'MNI', state: 'Gujarat' },
    { name: 'NIKOL', code: 'NIK', state: 'Gujarat' },
    { name: 'VASTRAPUR', code: 'VAS', state: 'Gujarat' },
    { name: 'KATHWADA G.I.D.C', code: 'KTH', state: 'Gujarat' },
    { name: 'VASNA A.P.M.C.', code: 'VA1', state: 'Gujarat' },
    { name: 'GITA MANDIR', code: 'GIT', state: 'Gujarat' },
    { name: 'RAKANPUR-BHADAJ', code: 'RBH', state: 'Gujarat' },
    { name: 'C.T.M', code: 'CTM', state: 'Gujarat' },
    { name: 'BAKROL G.I.D.C BUJRANG', code: 'BAK', state: 'Gujarat' },
    { name: 'VEJALPUR', code: 'VEJ', state: 'Gujarat' },
    { name: 'K.K. NAGAR', code: 'KKN', state: 'Gujarat' },
    { name: 'NEW CLOTH GHANTAKARNA MARKET', code: 'NCG', state: 'Gujarat' },
    { name: 'MEMCO', code: 'MEM', state: 'Gujarat' },
    { name: 'SOUTH BOPAL', code: 'SBO', state: 'Gujarat' },
    { name: 'MIRZAPUR', code: 'MIR', state: 'Gujarat' },
    { name: 'SINDHU BHAVAN', code: 'SIN', state: 'Gujarat' },
    { name: 'PALDI', code: 'PLD', state: 'Gujarat' },
    { name: 'VASTRAL', code: 'VA2', state: 'Gujarat' },
    { name: 'VINZOL', code: 'VIN', state: 'Gujarat' },
    { name: 'NEW RANIP', code: 'NRA', state: 'Gujarat' },
    { name: 'ANKUR CHAR RASTA', code: 'ANC', state: 'Gujarat' },
    { name: 'NANA CHILODA', code: 'NCH', state: 'Gujarat' },
    { name: 'HANSPURA', code: 'HAN', state: 'Gujarat' },
    { name: 'DHANDHUKA', code: 'DHA', state: 'Gujarat' },
    { name: 'DHOLKA', code: 'DHO', state: 'Gujarat' },
    { name: 'VATAMAN CHOKDI', code: 'VTC', state: 'Gujarat' },
    { name: 'BAVLA', code: 'BAV', state: 'Gujarat' },
    { name: 'SANAND', code: 'SAN', state: 'Gujarat' },
    { name: 'MANDAL', code: 'MA1', state: 'Gujarat' },
    { name: 'VIRAMGAM', code: 'VIR', state: 'Gujarat' },
    { name: 'DHOLERA', code: 'DH1', state: 'Gujarat' },
    { name: 'GANDHINAGAR SECTOR 3', code: 'GAN', state: 'Gujarat' },
    { name: 'GANDHINAGAR KUDASAN', code: 'GAK', state: 'Gujarat' },
    { name: 'DAHEGAM', code: 'DAH', state: 'Gujarat' },
    { name: 'MANSA', code: 'MAN', state: 'Gujarat' },
    { name: 'KALOL', code: 'KLL', state: 'Gujarat' },
    { name: 'CHHATRAL', code: 'CHH', state: 'Gujarat' },
    { name: 'HIMMATNAGAR', code: 'HIM', state: 'Gujarat' },
    { name: 'IDAR', code: 'IDA', state: 'Gujarat' },
    { name: 'MODASA', code: 'MOD', state: 'Gujarat' },
    { name: 'BAYAD', code: 'BAY', state: 'Gujarat' },
    { name: 'KHEDBRAHMA', code: 'KHD', state: 'Gujarat' },
    { name: 'PRANTIJ', code: 'PRA', state: 'Gujarat' },
    { name: 'SULTANPURA VADODARA', code: 'SUL', state: 'Gujarat' },
    { name: 'ALKAPURI VADODARA', code: 'ALK', state: 'Gujarat' },
    { name: 'MAKARPURA G.I.D.C VADODARA', code: 'MAK', state: 'Gujarat' },
    { name: 'CHHANI JAKATNAKA VADODARA', code: 'CHJ', state: 'Gujarat' },
    { name: 'AJWA CHOKDI VADODARA', code: 'AJW', state: 'Gujarat' },
    { name: 'GOTRI VADODARA', code: 'GTV', state: 'Gujarat' },
    { name: 'SAMA-SAVLI VADODARA', code: 'SAM', state: 'Gujarat' },
    { name: 'VASNA-BHAYLI VADODADRA', code: 'VAB', state: 'Gujarat' },
    { name: 'SAVLI', code: 'SAV', state: 'Gujarat' },
    { name: 'WAGHODIA ROAD PARIVAR CHOKDI VADODARA', code: 'WAG', state: 'Gujarat' },
    { name: 'PRATAPNAGAR VADODARA', code: 'PRT', state: 'Gujarat' },
    { name: 'TARAPUR', code: 'TAR', state: 'Gujarat' },
    { name: 'NADIAD', code: 'NAD', state: 'Gujarat' },
    { name: 'ANAND', code: 'ANA', state: 'Gujarat' },
    { name: 'UMRETH', code: 'UMR', state: 'Gujarat' },
    { name: 'KHEDA', code: 'KHE', state: 'Gujarat' },
    { name: 'KAPADVANJ', code: 'KAP', state: 'Gujarat' },
    { name: 'KATHLAL', code: 'KAT', state: 'Gujarat' },
    { name: 'VALLABH VIDHYANAGAR', code: 'VAL', state: 'Gujarat' },
    { name: 'PETLAD', code: 'PET', state: 'Gujarat' },
    { name: 'BORSAD', code: 'BOR', state: 'Gujarat' },
    { name: 'KHAMBHAT', code: 'KHA', state: 'Gujarat' },
    { name: 'DAHOD', code: 'DHD', state: 'Gujarat' },
    { name: 'PIPLOD', code: 'PIP', state: 'Gujarat' },
    { name: 'GODHRA', code: 'GOD', state: 'Gujarat' },
    { name: 'HALOL', code: 'HAL', state: 'Gujarat' },
    { name: 'LUNAWADA', code: 'LUN', state: 'Gujarat' },
    { name: 'KALOL ( PANCHMAHAL )', code: 'KA1', state: 'Gujarat' },
    { name: 'PADRA', code: 'PAD', state: 'Gujarat' },
    { name: 'DABHOI', code: 'DAB', state: 'Gujarat' },
    { name: 'BODELI', code: 'BOD', state: 'Gujarat' },
    { name: 'CHHOTA UDEPUR', code: 'CHU', state: 'Gujarat' },
    { name: 'VARACHHA', code: 'VAR', state: 'Gujarat' },
    { name: 'MOTA VARACHHA', code: 'MVA', state: 'Gujarat' },
    { name: 'MAHIDHARPURA', code: 'MHD', state: 'Gujarat' },
    { name: 'A.K.ROAD', code: 'AKR', state: 'Gujarat' },
    { name: 'HIRABAUG', code: 'HIR', state: 'Gujarat' },
    { name: 'KATARGAM', code: 'KAG', state: 'Gujarat' },
    { name: 'ATHWALINES', code: 'ATH', state: 'Gujarat' },
    { name: 'ADAJAN', code: 'ADA', state: 'Gujarat' },
    { name: 'PAL', code: 'PAL', state: 'Gujarat' },
    { name: 'SARTHANA JAKAT NAKA', code: 'SJN', state: 'Gujarat' },
    { name: 'UDHNA', code: 'UDH', state: 'Gujarat' },
    { name: 'KAMREJ', code: 'KAM', state: 'Gujarat' },
    { name: 'SAHARA DARWAJA', code: 'SHD', state: 'Gujarat' },
    { name: 'BHATAR', code: 'BHT', state: 'Gujarat' },
    { name: 'SACHIN', code: 'SAC', state: 'Gujarat' },
    { name: 'BHAGAL', code: 'BHG', state: 'Gujarat' },
    { name: 'VESU', code: 'VES', state: 'Gujarat' },
    { name: 'PARVAT PATIYA', code: 'PVP', state: 'Gujarat' },
    { name: 'PARLE POINT GHOD DOD ROAD', code: 'PPG', state: 'Gujarat' },
    { name: 'RANDER', code: 'RND', state: 'Gujarat' },
    { name: 'YOGI CHOWK', code: 'YOC', state: 'Gujarat' },
    { name: 'CHAUTA BAZAR', code: 'CHB', state: 'Gujarat' },
    { name: 'ALTHAN', code: 'ALT', state: 'Gujarat' },
    { name: 'AMROLI', code: 'AMR', state: 'Gujarat' },
    { name: 'KIM', code: 'KIM', state: 'Gujarat' },
    { name: 'DABHOLI', code: 'DBH', state: 'Gujarat' },
    { name: 'NAVSARI', code: 'NAV', state: 'Gujarat' },
    { name: 'CHIKHLI', code: 'CHK', state: 'Gujarat' },
    { name: 'VALSAD', code: 'VLS', state: 'Gujarat' },
    { name: 'DHARMPUR', code: 'DHP', state: 'Gujarat' },
    { name: 'VAPI', code: 'VAP', state: 'Gujarat' },
    { name: 'ANKLESHWAR STATION ROAD', code: 'ASR', state: 'Gujarat' },
    { name: 'ANKLESHWAR G.I.D.C', code: 'AGI', state: 'Gujarat' },
    { name: 'GOLDEN POINT CHOKDI', code: 'GPC', state: 'Gujarat' },
    { name: 'BHARUCH', code: 'BRC', state: 'Gujarat' },
    { name: 'BILIMORA', code: 'BLM', state: 'Gujarat' },
    { name: 'BARDOLI', code: 'BRD', state: 'Gujarat' },
    { name: 'VYARA', code: 'VYA', state: 'Gujarat' },
    { name: 'MANDVI', code: 'MDV', state: 'Gujarat' },
    { name: 'RAJPUTPARA', code: 'RJP', state: 'Gujarat' },
    { name: 'SONIBAZAR', code: 'SNB', state: 'Gujarat' },
    { name: 'UNIVERSITY', code: 'UNI', state: 'Gujarat' },
    { name: 'DANAPITH', code: 'DNP', state: 'Gujarat' },
    { name: 'BHAKTINAGAR', code: 'BKT', state: 'Gujarat' },
    { name: 'RAJKOT YARD OLD', code: 'RYO', state: 'Gujarat' },
    { name: 'RAJKOT YARD NEW BEDI YARD', code: 'RNB', state: 'Gujarat' },
    { name: 'RAIYA ROAD', code: 'RAR', state: 'Gujarat' },
    { name: 'AMIN MARG', code: 'AMM', state: 'Gujarat' },
    { name: 'KISHANPARA', code: 'KSP', state: 'Gujarat' },
    { name: 'YAGNIK ROAD', code: 'YGR', state: 'Gujarat' },
    { name: 'METODA', code: 'MTD', state: 'Gujarat' },
    { name: 'MAVDI', code: 'MVD', state: 'Gujarat' },
    { name: 'MAVDI ROAD BAPASITARAM CHOWK', code: 'MRB', state: 'Gujarat' },
    { name: 'GOVERDHAN CHOWK 150FT RING ROAD', code: 'GCR', state: 'Gujarat' },
    { name: 'RANCHHODNAGAR', code: 'RCH', state: 'Gujarat' },
    { name: 'SORATHIYAWADI', code: 'SRW', state: 'Gujarat' },
    { name: 'NANA MAVA MAIN ROAD', code: 'NMM', state: 'Gujarat' },
    { name: 'NAVAGAM', code: 'NVG', state: 'Gujarat' },
    { name: 'GONDAL CHOKDI', code: 'GDC', state: 'Gujarat' },
    { name: 'GUNDAWADI', code: 'GDW', state: 'Gujarat' },
    { name: 'KARANPARA', code: 'KRP', state: 'Gujarat' },
    { name: 'MADHAPAR CHOKDI', code: 'MDC', state: 'Gujarat' },
    { name: 'BAJARANGWADI', code: 'BJW', state: 'Gujarat' },
    { name: 'KOTHARIYA ROAD', code: 'KTR', state: 'Gujarat' },
    { name: 'SADHU VASWANI ROAD', code: 'SVR', state: 'Gujarat' },
    { name: 'AYODHYA CHOWK 150 FT', code: 'AYC', state: 'Gujarat' },
    { name: 'JUNCTION PLOT', code: 'JNP', state: 'Gujarat' },
    { name: 'SPEEDWELL PARTY CHOWK', code: 'SPC', state: 'Gujarat' },
    { name: 'SAPAR-VERAVAL', code: 'SPV', state: 'Gujarat' },
    { name: 'KUVADVA', code: 'KUV', state: 'Gujarat' },
    { name: 'WANKANER', code: 'WNK', state: 'Gujarat' },
    { name: 'JETPUR', code: 'JTP', state: 'Gujarat' },
    { name: 'JETPUR YARD', code: 'JPY', state: 'Gujarat' },
    { name: 'JASDAN', code: 'JSD', state: 'Gujarat' },
    { name: 'VINCHHIYA', code: 'VCH', state: 'Gujarat' },
    { name: 'GONDAL VICTORY TALKIES', code: 'GVT', state: 'Gujarat' },
    { name: 'GONDAL BUS STAND ROAD', code: 'GBS', state: 'Gujarat' },
    { name: 'GONDAL YARD', code: 'GYD', state: 'Gujarat' },
    { name: 'GONDAL G.I.D.C JAMVADI', code: 'GGJ', state: 'Gujarat' },
    { name: 'BHUNAVA CHOKDI', code: 'BNC', state: 'Gujarat' },
    { name: 'HALVAD', code: 'HLV', state: 'Gujarat' },
    { name: 'KALAVAD', code: 'KLV', state: 'Gujarat' },
    { name: 'PADDHARI', code: 'PDH', state: 'Gujarat' },
    { name: 'JAM KADORANA', code: 'JKD', state: 'Gujarat' },
    { name: 'MORBI CITY', code: 'MBC', state: 'Gujarat' },
    { name: 'MORBI YARD NEW BUS STAND', code: 'MYN', state: 'Gujarat' },
    { name: 'MORBI SAMAKATHA', code: 'MSK', state: 'Gujarat' },
    { name: 'MORBI MAHENDRA NAGAR CHOKDI', code: 'MMN', state: 'Gujarat' },
    { name: 'TANKARA', code: 'TNK', state: 'Gujarat' },
    { name: 'LAJAI CHOKDI', code: 'LJC', state: 'Gujarat' },
    { name: 'SURENDRANAGAR', code: 'SRN', state: 'Gujarat' },
    { name: 'JORAVARNAGAR', code: 'JRV', state: 'Gujarat' },
    { name: 'WADHWAN', code: 'WDH', state: 'Gujarat' },
    { name: 'THANGADH', code: 'THA', state: 'Gujarat' },
    { name: 'LIMBDI', code: 'LIM', state: 'Gujarat' },
    { name: 'CHOTILA', code: 'CHO', state: 'Gujarat' },
    { name: 'DHRANGADHRA', code: 'DRG', state: 'Gujarat' },
    { name: 'SAYLA', code: 'SAY', state: 'Gujarat' },
    { name: 'PATDI', code: 'PTD', state: 'Gujarat' },
    { name: 'JUNAGADH MANGNATH ROAD', code: 'JMR', state: 'Gujarat' },
    { name: 'JUNAGADH M G ROAD', code: 'JMG', state: 'Gujarat' },
    { name: 'JUNAGADH YARD DAULATPURA', code: 'JYD', state: 'Gujarat' },
    { name: 'JUNAGADH ZANZARDA ROAD', code: 'JZR', state: 'Gujarat' },
    { name: 'JUNAGADH MADHURAM', code: 'JMD', state: 'Gujarat' },
    { name: 'VANTHLI', code: 'VNT', state: 'Gujarat' },
    { name: 'BHESHAN', code: 'BHE', state: 'Gujarat' },
    { name: 'KESHOD AMBAVADI', code: 'KAV', state: 'Gujarat' },
    { name: 'KESHOD BUS STAND', code: 'KBS', state: 'Gujarat' },
    { name: 'KODINAR', code: 'KOD', state: 'Gujarat' },
    { name: 'UPLETA', code: 'UPL', state: 'Gujarat' },
    { name: 'PANELI', code: 'PNL', state: 'Gujarat' },
    { name: 'BHAYAVADAR', code: 'BYV', state: 'Gujarat' },
    { name: 'TALALA', code: 'TLL', state: 'Gujarat' },
    { name: 'CHORVAD', code: 'CRV', state: 'Gujarat' },
    { name: 'DHORAJI', code: 'DRJ', state: 'Gujarat' },
    { name: 'UNA', code: 'UNA', state: 'Gujarat' },
    { name: 'VERAVAL', code: 'VRV', state: 'Gujarat' },
    { name: 'VISAVADAR', code: 'VSV', state: 'Gujarat' },
    { name: 'MANAVADAR', code: 'MNV', state: 'Gujarat' },
    { name: 'BATWA', code: 'BTW', state: 'Gujarat' },
    { name: 'BILKHA', code: 'BLK', state: 'Gujarat' },
    { name: 'MANGROL', code: 'MGR', state: 'Gujarat' },
    { name: 'PRACHI', code: 'PRC', state: 'Gujarat' },
    { name: 'SUTRAPADA', code: 'SUT', state: 'Gujarat' },
    { name: 'SUTRAPADA FATAK', code: 'STF', state: 'Gujarat' },
    { name: 'MENDARDA', code: 'MND', state: 'Gujarat' },
    { name: 'GADU', code: 'GDU', state: 'Gujarat' },
    { name: 'MALIYA HATINA', code: 'MLH', state: 'Gujarat' },
    { name: 'JAMNAGAR GRAIN MARKET', code: 'JGM', state: 'Gujarat' },
    { name: 'JAMNAGAR UDHYOG DIGVIJAY', code: 'JUD', state: 'Gujarat' },
    { name: 'DARED', code: 'DRD', state: 'Gujarat' },
    { name: 'LAMBA', code: 'LMB', state: 'Gujarat' },
    { name: 'RAVAL', code: 'RVL', state: 'Gujarat' },
    { name: 'PORBANDAR M.G ROAD', code: 'PMR', state: 'Gujarat' },
    { name: 'PORBANDAR HOSPITAL ROAD', code: 'PHR', state: 'Gujarat' },
    { name: 'MADHAVPUR GHED', code: 'MDG', state: 'Gujarat' },
    { name: 'DHROL', code: 'DHR', state: 'Gujarat' },
    { name: 'KHAMBHALIA', code: 'KHB', state: 'Gujarat' },
    { name: 'JAM JODHPUR', code: 'JJP', state: 'Gujarat' },
    { name: 'LALPUR', code: 'LLP', state: 'Gujarat' },
    { name: 'BHATIYA', code: 'BHA', state: 'Gujarat' },
    { name: 'MITHAPUR', code: 'MTP', state: 'Gujarat' },
    { name: 'DWARKA', code: 'DWK', state: 'Gujarat' },
    { name: 'RANAVAV', code: 'RNV', state: 'Gujarat' },
    { name: 'KUTIYANA', code: 'KTY', state: 'Gujarat' },
    { name: 'RANA KANDORNA', code: 'RNK', state: 'Gujarat' },
    { name: 'BHANVAD', code: 'BNV', state: 'Gujarat' },
    { name: 'OKHA', code: 'OKH', state: 'Gujarat' },
    { name: 'NIKAVA', code: 'NKV', state: 'Gujarat' },
    { name: 'BHAVNAGAR VORABAJAR', code: 'BHV', state: 'Gujarat' },
    { name: 'BHAVNAGAR SHASTRINAGAR', code: 'BHS', state: 'Gujarat' },
    { name: 'BHAVNAGAR SANSKAR MANDAL', code: 'BSM', state: 'Gujarat' },
    { name: 'BHAVNAGAR KALIYABID', code: 'BKL', state: 'Gujarat' },
    { name: 'BHAVNAGAR KALANALA', code: 'BKN', state: 'Gujarat' },
    { name: 'BHAVNAGAR YARD CHITRA', code: 'BYC', state: 'Gujarat' },
    { name: 'VARTEJ', code: 'VTJ', state: 'Gujarat' },
    { name: 'AMRELI', code: 'AML', state: 'Gujarat' },
    { name: 'AMRELI YARD', code: 'AMY', state: 'Gujarat' },
    { name: 'CHITAL', code: 'CTL', state: 'Gujarat' },
    { name: 'DHARI', code: 'DHI', state: 'Gujarat' },
    { name: 'CHALALA', code: 'CHL', state: 'Gujarat' },
    { name: 'KHAMBHA (GIR)', code: 'KHG', state: 'Gujarat' },
    { name: 'KUNKAVAV', code: 'KKV', state: 'Gujarat' },
    { name: 'DERDI KUMBHAJI', code: 'DKM', state: 'Gujarat' },
    { name: 'BOTAD HIRA BAZZAR', code: 'BHB', state: 'Gujarat' },
    { name: 'BOTAD YARD', code: 'BTY', state: 'Gujarat' },
    { name: 'BOTAD TOWER ROAD', code: 'BTR', state: 'Gujarat' },
    { name: 'RANPUR', code: 'RNP', state: 'Gujarat' },
    { name: 'BARVALA', code: 'BRV', state: 'Gujarat' },
    { name: 'SAVARKUNDLA', code: 'SVK', state: 'Gujarat' },
    { name: 'DHOLA JUNCTION', code: 'DHJ', state: 'Gujarat' },
    { name: 'SIHOR', code: 'SHR', state: 'Gujarat' },
    { name: 'TALAJA MAIN BAZAR', code: 'TMB', state: 'Gujarat' },
    { name: 'ALANG', code: 'ALG', state: 'Gujarat' },
    { name: 'BAGASARA', code: 'BGS', state: 'Gujarat' },
    { name: 'BABRA', code: 'BBR', state: 'Gujarat' },
    { name: 'RAJULA', code: 'RJL', state: 'Gujarat' },
    { name: 'JAFRABAD', code: 'JFR', state: 'Gujarat' },
    { name: 'TIMBI', code: 'TIM', state: 'Gujarat' },
    { name: 'GARIYADHAR', code: 'GRD', state: 'Gujarat' },
    { name: 'DHASA', code: 'DHS', state: 'Gujarat' },
    { name: 'MAHUVA', code: 'MHV', state: 'Gujarat' },
    { name: 'MAHUVA YARD', code: 'MHY', state: 'Gujarat' },
    { name: 'PALITANA BUS STAND', code: 'PBS', state: 'Gujarat' },
    { name: 'DAMNAGAR', code: 'DMN', state: 'Gujarat' },
    { name: 'JESAR', code: 'JSR', state: 'Gujarat' },
    { name: 'GADHADA', code: 'GDH', state: 'Gujarat' },
    { name: 'VALLABHIPUR', code: 'VLP', state: 'Gujarat' },
    { name: 'THARA', code: 'THR', state: 'Gujarat' },
    { name: 'LAKHANI', code: 'LKH', state: 'Gujarat' },
    { name: 'UNJHA', code: 'UNJ', state: 'Gujarat' },
    { name: 'PALANPUR', code: 'PLP', state: 'Gujarat' },
    { name: 'AMBAJI', code: 'AMB', state: 'Gujarat' },
    { name: 'PATAN', code: 'PAT', state: 'Gujarat' },
    { name: 'CHANASMA', code: 'CHS', state: 'Gujarat' },
    { name: 'KADI', code: 'KDI', state: 'Gujarat' },
    { name: 'SIDDHPUR', code: 'SDP', state: 'Gujarat' },
    { name: 'SAMI', code: 'SMI', state: 'Gujarat' },
    { name: 'VISNAGAR', code: 'VNG', state: 'Gujarat' },
    { name: 'BHABHAR', code: 'BHR', state: 'Gujarat' },
    { name: 'RADHANPUR', code: 'RDP', state: 'Gujarat' },
    { name: 'MEHSANA', code: 'MSN', state: 'Gujarat' },
    { name: 'BHILDI', code: 'BHD', state: 'Gujarat' },
    { name: 'DHANERA', code: 'DNR', state: 'Gujarat' },
    { name: 'PANTHAWADA', code: 'PTW', state: 'Gujarat' },
    { name: 'DIYODAR', code: 'DYD', state: 'Gujarat' },
    { name: 'HARIJ', code: 'HRJ', state: 'Gujarat' },
    { name: 'SANKHESHWAR', code: 'SKW', state: 'Gujarat' },
    { name: 'THARAD', code: 'TRD', state: 'Gujarat' },
    { name: 'VAV', code: 'VAV', state: 'Gujarat' },
    { name: 'VIJAPUR', code: 'VJP', state: 'Gujarat' },
    { name: 'BAHUCHARAJI', code: 'BAH', state: 'Gujarat' },
    { name: 'DEESA', code: 'DES', state: 'Gujarat' },
    { name: 'VARAHI', code: 'VRH', state: 'Gujarat' },
    { name: 'SANTALPUR', code: 'STP', state: 'Gujarat' },
    { name: 'SIHORI', code: 'SHI', state: 'Gujarat' },
    { name: 'BHUJ CITY', code: 'BHC', state: 'Gujarat' },
    { name: 'BHUJ NEW STATION ROAD', code: 'BNS', state: 'Gujarat' },
    { name: 'BHUJ YARD', code: 'BHY', state: 'Gujarat' },
    { name: 'BHUJ JUBILEE CIRCLE', code: 'BJC', state: 'Gujarat' },
    { name: 'BHACHAU', code: 'BHU', state: 'Gujarat' },
    { name: 'GANDHIDHAM ZANDA CHOWK', code: 'GZC', state: 'Gujarat' },
    { name: 'GANDHIDHAM SONIBAJAR', code: 'GSB', state: 'Gujarat' },
    { name: 'ANJAR', code: 'ANJ', state: 'Gujarat' },
    { name: 'NALIYA', code: 'NLY', state: 'Gujarat' },
    { name: 'VARMANAGAR (VAYA NALIYA)', code: 'VMN', state: 'Gujarat' },
    { name: 'KOTHARA', code: 'KOT', state: 'Gujarat' },
    { name: 'VAYOR (VAYA NALIYA)', code: 'VYR', state: 'Gujarat' },
    { name: 'JAKHAU BANDAR (VAYA NALIYA)', code: 'JKB', state: 'Gujarat' },
    { name: 'MOTHALA (VAYA NALIYA)', code: 'MTH', state: 'Gujarat' },
    { name: 'RAPAR', code: 'RAP', state: 'Gujarat' },
    { name: 'MADHAPAR HIGHWAY', code: 'MPH', state: 'Gujarat' },
    { name: 'MADHAPAR CITY', code: 'MPC', state: 'Gujarat' },
    { name: 'ADIPUR', code: 'ADP', state: 'Gujarat' },
    { name: 'ADESAR', code: 'ADS', state: 'Gujarat' },
    { name: 'MUNDRA', code: 'MDR', state: 'Gujarat' },
    { name: 'NAKHTRANA', code: 'NKT', state: 'Gujarat' },
    { name: 'SAMKHIYALI', code: 'SMK', state: 'Gujarat' },
    { name: 'GADHSISA', code: 'GDS', state: 'Gujarat' },
    { name: 'DAYAPAR', code: 'DYP', state: 'Gujarat' },
    { name: 'OPERA HOUSE', code: 'OPH', state: 'Maharashtra' },
    { name: 'BHULESHWAR', code: 'BHL', state: 'Maharashtra' },
    { name: 'ANDHERI', code: 'AND', state: 'Maharashtra' },
    { name: 'BORIVALI (EAST)', code: 'BOE', state: 'Maharashtra' },
    { name: 'DADAR (WEST)', code: 'DAW', state: 'Maharashtra' },
    { name: 'DOMBIVLI', code: 'DMB', state: 'Maharashtra' },
    { name: 'GHATKOPAR TILAK ROAD', code: 'GTR', state: 'Maharashtra' },
    { name: 'PANVEL', code: 'PNV', state: 'Maharashtra' },
    { name: 'KALYAN', code: 'KLY', state: 'Maharashtra' },
    { name: 'MALAD (EAST)', code: 'MAE', state: 'Maharashtra' },
    { name: 'MALAD (WEST)', code: 'MAW', state: 'Maharashtra' },
    { name: 'MULUND', code: 'MLD', state: 'Maharashtra' },
    { name: 'NAGDEVI', code: 'NGD', state: 'Maharashtra' },
    { name: 'VASHI', code: 'VSH', state: 'Maharashtra' },
    { name: 'VASAI', code: 'VSI', state: 'Maharashtra' },
    { name: 'ULHASNAGAR', code: 'ULH', state: 'Maharashtra' },
    { name: 'AMBARNATH', code: 'AMN', state: 'Maharashtra' },
    { name: 'THANE', code: 'THN', state: 'Maharashtra' },
    { name: 'GHATKOPAR KAILASH PLAZA', code: 'GKP', state: 'Maharashtra' },
    { name: 'BHIWANDI', code: 'BWD', state: 'Maharashtra' },
    { name: 'BORIVALI (WEST)', code: 'BOW', state: 'Maharashtra' },
    { name: 'SANTACRUZ', code: 'STC', state: 'Maharashtra' },
    { name: 'B.K.C', code: 'BKC', state: 'Maharashtra' },
    { name: 'BHAYANDAR', code: 'BYD', state: 'Maharashtra' },
    { name: 'DELHI CHANDNI CHOWK', code: 'DCC', state: 'Delhi' },
    { name: 'DELHI KAROL BAGH', code: 'DKB', state: 'Delhi' },
    { name: 'RAIPUR', code: 'RPR', state: 'Chhattisgarh' },
    { name: 'PATNA', code: 'PTN', state: 'Bihar' },
    { name: 'GOA-PANAJI', code: 'GPN', state: 'Goa' },
    { name: 'GOA-VASCO', code: 'GVS', state: 'Goa' },
    { name: 'KOLKATA', code: 'KOL', state: 'West Bengal' },
    { name: 'CHENNAI', code: 'CHN', state: 'Tamil Nadu' },
    { name: 'BANGALORE', code: 'BGL', state: 'Karnataka' },
    { name: 'DEHRADUN', code: 'DEH', state: 'Uttarakhand' },
    { name: 'BELGAUM', code: 'BLG', state: 'Karnataka' },
    { name: 'TELANGANA-ANDHRA PRADESH', code: 'TAP', state: 'Telangana' },
    { name: 'BEGUM BAJAR HYDERABAD', code: 'BBH', state: 'Telangana' },
    { name: 'RANIGANJ SIKANDARABAD', code: 'RNS', state: 'Telangana' },
    { name: 'HYDERABAD', code: 'HYD', state: 'Telangana' },
    { name: 'VISAKHAPATNAM', code: 'VSK', state: 'Andhra Pradesh' },
    { name: 'VIJAYWADA', code: 'VJW', state: 'Andhra Pradesh' },
    { name: 'BANJARA JUBILEE HYDERABAD', code: 'BJH', state: 'Telangana' },
    { name: 'RAJASTHAN', code: 'RAJ', state: 'Rajasthan' },
    { name: 'JODHPUR', code: 'JDP', state: 'Rajasthan' },
    { name: 'AJMER', code: 'AJM', state: 'Rajasthan' },
    { name: 'JAIPUR', code: 'JPR', state: 'Rajasthan' },
    { name: 'SANCHORE', code: 'SNC', state: 'Rajasthan' },
    { name: 'BIKANER', code: 'BIK', state: 'Rajasthan' },
    { name: 'BARMER', code: 'BMR', state: 'Rajasthan' },
    { name: 'UDAIPUR', code: 'UDP', state: 'Rajasthan' },
    { name: 'BANSWARA', code: 'BAN', state: 'Rajasthan' },
    { name: 'BHILWARA', code: 'BHI', state: 'Rajasthan' },
    { name: 'KOTA', code: 'KTA', state: 'Rajasthan' },
    { name: 'BUNDI', code: 'BND', state: 'Rajasthan' },
    { name: 'KISHANGADH', code: 'KSG', state: 'Rajasthan' },
    { name: 'PALI', code: 'PLI', state: 'Rajasthan' },
    { name: 'NAGAUR', code: 'NGR', state: 'Rajasthan' },
    { name: 'ABU ROAD', code: 'ABR', state: 'Rajasthan' },
    { name: 'BEAWAR', code: 'BWR', state: 'Rajasthan' },
    { name: 'KANKROLI', code: 'KNK', state: 'Rajasthan' },
    { name: 'CHITTORGARH', code: 'CTG', state: 'Rajasthan' },
    { name: 'BALOTRA', code: 'BLT', state: 'Rajasthan' },
    { name: 'DUNGARPUR', code: 'DNG', state: 'Rajasthan' },
    { name: 'NIMBAHERA', code: 'NMB', state: 'Rajasthan' },
    { name: 'M P', code: 'MPX', state: 'Madhya Pradesh' },
    { name: 'BHOPAL', code: 'BPL', state: 'Madhya Pradesh' },
    { name: 'INDORE', code: 'IND', state: 'Madhya Pradesh' },
    { name: 'UJJAIN', code: 'UJN', state: 'Madhya Pradesh' },
    { name: 'GWALIOR', code: 'GWL', state: 'Madhya Pradesh' },
    { name: 'RATLAM', code: 'RTM', state: 'Madhya Pradesh' },
    { name: 'JHABUA', code: 'JHB', state: 'Madhya Pradesh' },
    { name: 'MAHARASHTRA', code: 'MHS', state: 'Maharashtra' },
    { name: 'KOLHAPUR', code: 'KLP', state: 'Maharashtra' },
    { name: 'NASHIK', code: 'NSK', state: 'Maharashtra' },
    { name: 'JALGAON', code: 'JLG', state: 'Maharashtra' },
    { name: 'PUNE MARKET YARD', code: 'PMY', state: 'Maharashtra' },
    { name: 'NAGPUR', code: 'NGP', state: 'Maharashtra' },
    { name: 'AKOLA', code: 'AKL', state: 'Maharashtra' },
    { name: 'YAVATMAL', code: 'YTL', state: 'Maharashtra' },
    { name: 'MALKAPUR', code: 'MKP', state: 'Maharashtra' },
    { name: 'PUNE DAGDUSHETH', code: 'PDG', state: 'Maharashtra' },
    { name: 'PUNE PIMPRI', code: 'PMP', state: 'Maharashtra' },
    { name: 'SATARA', code: 'STR', state: 'Maharashtra' },
    { name: 'AMRAVATI', code: 'AMV', state: 'Maharashtra' },
    { name: 'SANGLI', code: 'SGL', state: 'Maharashtra' },
    { name: 'HARYANA', code: 'HRY', state: 'Haryana' },
    { name: 'CHANDIGARH', code: 'CHD', state: 'Chandigarh' },
    { name: 'YAMUNANAGAR', code: 'YNG', state: 'Haryana' },
    { name: 'PANIPAT', code: 'PNP', state: 'Haryana' },
    { name: 'GURGAON (GURUGRAM)', code: 'GRG', state: 'Haryana' },
    { name: 'HISAR', code: 'HSR', state: 'Haryana' },
    { name: 'ROHTAK', code: 'RTK', state: 'Haryana' },
    { name: 'KARNAL', code: 'KRL', state: 'Haryana' },
    { name: 'U P', code: 'UPX', state: 'Uttar Pradesh' },
    { name: 'AGRA', code: 'AGR', state: 'Uttar Pradesh' },
    { name: 'NOIDA', code: 'NOI', state: 'Uttar Pradesh' },
    { name: 'SAHARANPUR', code: 'SRP', state: 'Uttar Pradesh' },
    { name: 'MEERUT', code: 'MRT', state: 'Uttar Pradesh' },
    { name: 'KANPUR', code: 'KNP', state: 'Uttar Pradesh' },
    { name: 'BANARAS', code: 'BNR', state: 'Uttar Pradesh' },
    { name: 'KERALA', code: 'KER', state: 'Kerala' },
    { name: 'KOCHIN', code: 'KOC', state: 'Kerala' },
    { name: 'CALICUT', code: 'CLT', state: 'Kerala' },
  ];

  for (const city of cities) {
    await prisma.city.upsert({
      where: { code: city.code },
      update: {
        name: city.name,
        state: city.state,
        isActive: true,
      },
      create: {
        ...city,
        isActive: true,
      },
    });
  }

  console.log('✅ Cities seeded successfully');
}
